[[plugins]]
repo = 'Shougo/dein.vim'
on_event = ['CursorHold', 'CmdlineEnter']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'
on_event = ['CursorHold', 'CmdlineEnter']

[[plugins]]
repo = 'mattn/vim-lsp-icons'
depends = 'vim-lsp'
on_event = ['CursorHold', 'CmdlineEnter']

[[plugins]]
repo = 'Shougo/vinarise'
on_cmd = 'Vinarise'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['eruby', 'ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['eruby', 'ruby']

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'
on_event = ['CursorHold', 'CmdlineEnter']

[[plugins]]
repo = 'junegunn/fzf.vim'
on_event = ['CursorHold', 'CmdlineEnter']

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = ['CursorHold', 'InsertEnter']

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
on_event = ['CursorHold', 'InsertEnter']
depends = 'vim-vsnip'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'
on_event = ['CursorHold', 'InsertEnter']
depends = 'vim-vsnip'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'xml']

[[plugins]]
repo = 'chrisbra/matchit'
on_event = ['CursorHold', 'InsertEnter']

[[plugins]]
repo = 'tpope/vim-endwise'
on_event = ['CursorHold', 'InsertEnter']

[[plugins]]
repo = 'NI57721/shakyo.vim'
on_event = ['CursorHold', 'CmdlineEnter']

[[plugins]]
repo = 'previm/previm'
on_event = ['CursorHold', 'InsertEnter']

[[plugins]]
repo = 'thinca/vim-themis'
on_event = ['CursorHold', 'CmdlineEnter']

[[plugins]]
repo = 'monaqa/dps-dial.vim'
on_map = '<Plug>(dps-dial-'
on_event = ['CursorHold', 'CursorMoved']

[[plugins]]
repo = 'NI57721/vim-socrates'
on_map = '<Plug>(socrates-'
on_event = ['CursorHold', 'CursorMoved']

[[plugins]]
repo = 'kana/vim-operator-user'
on_event = ['CursorHold', 'CursorMoved']

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = '<Plug>(operator-replace)'

[[plugins]]
repo = 'tweekmonster/helpful.vim'
on_event = ['CursorHold', 'CmdlineEnter']

[[plugins]]
repo = 'kei-s16/skkeleton-azik-kanatable'
on_source = 'skkeleton'

# [[plugins]]
# repo = 'NI57721/skkeleton-azik'
# rev = 'add-options'
# depends = ['denops.vim', 'skkeleton']
# repo = 'shg-eo/skkeleton-azik'

[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = ['CursorHold', 'InsertEnter']

[[plugins]]
repo = 'tyru/capture.vim'
on_event = ['CursorHold', 'InsertEnter']

[[plugins]]
repo = 'ryicoh/deepl.vim'
on_event = ['CursorHold', 'InsertEnter']

