[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'chrisbra/matchit'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'NI57721/shakyo.vim'

[[plugins]]
repo = 'previm/previm'

# [[plugins]]
# repo = 'shg-eo/skkeleton-azik'

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'monaqa/dps-dial.vim'

