[[plugins]]
repo = 'Shougo/dein.vim'
on_event = 'CmdlineEnter'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_event = ['CursorHold', 'CursorMoved']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'
on_event = ['CursorHold', 'CursorMoved']

[[plugins]]
repo = 'mattn/vim-lsp-icons'
depends = 'vim-lsp'
on_event = ['CursorHold', 'CursorMoved']

[[plugins]]
repo = 'Shougo/vinarise'
on_cmd = 'Vinarise'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['eruby', 'ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['eruby', 'ruby']

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'
on_event = 'CmdlineEnter'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
on_source = 'fzf'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_event = 'InsertEnter'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
depends = 'vim-vsnip'
on_source = 'vim-vsnip'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'
on_source = 'vim-vsnip'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'xml']

[[plugins]]
repo = 'chrisbra/matchit'
on_event = 'InsertEnter'

[[plugins]]
repo = 'tpope/vim-endwise'
on_event = 'InsertEnter'

[[plugins]]
repo = 'NI57721/shakyo.vim'
on_event = 'CmdlineEnter'

[[plugins]]
repo = 'previm/previm'
on_event = 'InsertEnter'

[[plugins]]
repo = 'thinca/vim-themis'
on_event = 'CmdlineEnter'

[[plugins]]
repo = 'monaqa/dps-dial.vim'
on_map = '<Plug>(dps-dial-'

[[plugins]]
repo = 'NI57721/vim-socrates'
on_map = '<Plug>(socrates-'

[[plugins]]
repo = 'kana/vim-operator-user'
on_event = ['CursorHold', 'CursorMoved']

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_source = 'vim-operator-user'

# [[plugins]]
# repo = 'shg-eo/skkeleton-azik'

