[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
# on_event = ['CursorHold', 'CursorMoved']

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = 'denops.vim'
# repo = 'NI57721/skkeleton'
# rev = 'fix-candidates'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-ui-native'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'tani/ddc-fuzzy'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-around'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'matsui54/ddc-buffer'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'LumaKernel/ddc-source-file'
depends = ['denops.vim', 'ddc.vim']

[[plugins]]
repo = 'Shougo/ddu.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-kind-file'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-column-filename'
depends = ['denops.vim', 'ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
depends = ['denops.vim', 'ddu.vim']

